resources:
- manager.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: ghcr.io/mirantiscontainers/boundless-operator
  newName: localhost:5001/boundless-operator
  newTag: dev.2
