apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: |-
      [
        {
          "apiVersion": "boundless.mirantis.com/v1alpha1",
          "kind": "Addon",
          "metadata": {
            "labels": {
              "app.kubernetes.io/created-by": "boundless-operator",
              "app.kubernetes.io/instance": "addon-sample",
              "app.kubernetes.io/managed-by": "kustomize",
              "app.kubernetes.io/name": "addon",
              "app.kubernetes.io/part-of": "boundless-operator"
            },
            "name": "addon-sample"
          },
          "spec": null
        },
        {
          "apiVersion": "boundless.mirantis.com/v1alpha1",
          "kind": "Blueprint",
          "metadata": {
            "labels": {
              "app.kubernetes.io/created-by": "boundless-operator",
              "app.kubernetes.io/instance": "blueprint-sample",
              "app.kubernetes.io/managed-by": "kustomize",
              "app.kubernetes.io/name": "blueprint",
              "app.kubernetes.io/part-of": "boundless-operator"
            },
            "name": "blueprint-sample"
          },
          "spec": null
        },
        {
          "apiVersion": "boundless.mirantis.com/v1alpha1",
          "kind": "Ingress",
          "metadata": {
            "labels": {
              "app.kubernetes.io/created-by": "boundless-operator",
              "app.kubernetes.io/instance": "ingress-sample",
              "app.kubernetes.io/managed-by": "kustomize",
              "app.kubernetes.io/name": "ingress",
              "app.kubernetes.io/part-of": "boundless-operator"
            },
            "name": "ingress-sample"
          },
          "spec": null
        },
        {
          "apiVersion": "boundless.mirantis.com/v1alpha1",
          "kind": "Manifest",
          "metadata": {
            "labels": {
              "app.kubernetes.io/created-by": "boundless-operator",
              "app.kubernetes.io/instance": "manifest-sample",
              "app.kubernetes.io/managed-by": "kustomize",
              "app.kubernetes.io/name": "manifest",
              "app.kubernetes.io/part-of": "boundless-operator"
            },
            "name": "manifest-sample"
          },
          "spec": null
        }
      ]
    capabilities: Basic Install
    createdAt: "2023-12-04T20:43:31Z"
    operators.operatorframework.io/builder: operator-sdk-v1.32.0
    operators.operatorframework.io/project_layout: go.kubebuilder.io/v3
  name: boundless-operator.v0.0.1
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: Addon is the Schema for the addons API
      displayName: Addon
      kind: Addon
      name: addons.boundless.mirantis.com
      version: v1alpha1
    - description: Blueprint is the Schema for the blueprints API
      displayName: Blueprint
      kind: Blueprint
      name: blueprints.boundless.mirantis.com
      version: v1alpha1
    - description: Ingress is the Schema for the ingresses API
      displayName: Ingress
      kind: Ingress
      name: ingresses.boundless.mirantis.com
      version: v1alpha1
    - description: Manifest is the Schema for the manifests API
      displayName: Manifest
      kind: Manifest
      name: manifests.boundless.mirantis.com
      version: v1alpha1
  description: boundless operator
  displayName: boundless-operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      clusterPermissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - events
          verbs:
          - create
          - patch
        - apiGroups:
          - boundless.mirantis.com
          resources:
          - addons
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - boundless.mirantis.com
          resources:
          - addons/finalizers
          verbs:
          - update
        - apiGroups:
          - boundless.mirantis.com
          resources:
          - addons/status
          verbs:
          - get
          - patch
          - update
        - apiGroups:
          - boundless.mirantis.com
          resources:
          - blueprints
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - boundless.mirantis.com
          resources:
          - blueprints/finalizers
          verbs:
          - update
        - apiGroups:
          - boundless.mirantis.com
          resources:
          - blueprints/status
          verbs:
          - get
          - patch
          - update
        - apiGroups:
          - boundless.mirantis.com
          resources:
          - ingresses
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - boundless.mirantis.com
          resources:
          - ingresses/finalizers
          verbs:
          - update
        - apiGroups:
          - boundless.mirantis.com
          resources:
          - ingresses/status
          verbs:
          - get
          - patch
          - update
        - apiGroups:
          - boundless.mirantis.com
          resources:
          - manifests
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - boundless.mirantis.com
          resources:
          - manifests/finalizers
          verbs:
          - update
        - apiGroups:
          - boundless.mirantis.com
          resources:
          - manifests/status
          verbs:
          - get
          - patch
          - update
        - apiGroups:
          - authentication.k8s.io
          resources:
          - tokenreviews
          verbs:
          - create
        - apiGroups:
          - authorization.k8s.io
          resources:
          - subjectaccessreviews
          verbs:
          - create
        serviceAccountName: boundless-operator-controller-manager
      deployments:
      - label:
          app.kubernetes.io/component: manager
          app.kubernetes.io/created-by: boundless-operator
          app.kubernetes.io/instance: controller-manager
          app.kubernetes.io/managed-by: kustomize
          app.kubernetes.io/name: deployment
          app.kubernetes.io/part-of: boundless-operator
          control-plane: controller-manager
        name: boundless-operator-controller-manager
        spec:
          replicas: 1
          selector:
            matchLabels:
              control-plane: controller-manager
          strategy: {}
          template:
            metadata:
              annotations:
                kubectl.kubernetes.io/default-container: manager
              labels:
                control-plane: controller-manager
            spec:
              affinity:
                nodeAffinity:
                  requiredDuringSchedulingIgnoredDuringExecution:
                    nodeSelectorTerms:
                    - matchExpressions:
                      - key: kubernetes.io/arch
                        operator: In
                        values:
                        - amd64
                        - arm64
                        - ppc64le
                        - s390x
                      - key: kubernetes.io/os
                        operator: In
                        values:
                        - linux
              containers:
              - args:
                - --secure-listen-address=0.0.0.0:8443
                - --upstream=http://127.0.0.1:8080/
                - --logtostderr=true
                - --v=0
                image: gcr.io/kubebuilder/kube-rbac-proxy:v0.13.1
                name: kube-rbac-proxy
                ports:
                - containerPort: 8443
                  name: https
                  protocol: TCP
                resources:
                  limits:
                    cpu: 500m
                    memory: 128Mi
                  requests:
                    cpu: 5m
                    memory: 64Mi
                securityContext:
                  allowPrivilegeEscalation: false
                  capabilities:
                    drop:
                    - ALL
              - args:
                - --health-probe-bind-address=:8081
                - --metrics-bind-address=127.0.0.1:8080
                - --leader-elect
                command:
                - /manager
                image: ghcr.io/mirantis/boundless-operator:latest
                livenessProbe:
                  httpGet:
                    path: /healthz
                    port: 8081
                  initialDelaySeconds: 15
                  periodSeconds: 20
                name: manager
                readinessProbe:
                  httpGet:
                    path: /readyz
                    port: 8081
                  initialDelaySeconds: 5
                  periodSeconds: 10
                resources:
                  limits:
                    cpu: 500m
                    memory: 128Mi
                  requests:
                    cpu: 10m
                    memory: 64Mi
                securityContext:
                  allowPrivilegeEscalation: false
                  capabilities:
                    drop:
                    - ALL
              securityContext:
                runAsNonRoot: true
              serviceAccountName: boundless-operator-controller-manager
              terminationGracePeriodSeconds: 10
      permissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - configmaps
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - coordination.k8s.io
          resources:
          - leases
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - ""
          resources:
          - events
          verbs:
          - create
          - patch
        serviceAccountName: boundless-operator-controller-manager
    strategy: deployment
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - app
  - operator
  links:
  - name: Boundless Operator
    url: https://boundless-operator.domain
  maturity: alpha
  provider:
    name: Mirantis
  version: 0.0.1
