# permissions for end users to view blueprints.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: blueprint-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: blueprint-operator
    app.kubernetes.io/part-of: blueprint-operator
    app.kubernetes.io/managed-by: kustomize
  name: blueprint-viewer-role
rules:
- apiGroups:
  - blueprint.mirantis.com
  resources:
  - blueprints
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - blueprint.mirantis.com
  resources:
  - blueprints/status
  verbs:
  - get
