---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - apps
  resources:
  - daemonsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - daemonsets/status
  verbs:
  - get
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - deployments/status
  verbs:
  - get
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - batch
  resources:
  - jobs/status
  verbs:
  - get
- apiGroups:
  - boundless.mirantis.com
  resources:
  - addons
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - boundless.mirantis.com
  resources:
  - addons/finalizers
  verbs:
  - update
- apiGroups:
  - boundless.mirantis.com
  resources:
  - addons/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - boundless.mirantis.com
  resources:
  - blueprints
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - boundless.mirantis.com
  resources:
  - blueprints/finalizers
  verbs:
  - update
- apiGroups:
  - boundless.mirantis.com
  resources:
  - blueprints/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - boundless.mirantis.com
  resources:
  - ingresses
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - boundless.mirantis.com
  resources:
  - ingresses/finalizers
  verbs:
  - update
- apiGroups:
  - boundless.mirantis.com
  resources:
  - ingresses/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - boundless.mirantis.com
  resources:
  - manifests
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - boundless.mirantis.com
  resources:
  - manifests/finalizers
  verbs:
  - update
- apiGroups:
  - boundless.mirantis.com
  resources:
  - manifests/status
  verbs:
  - get
  - patch
  - update
