apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
  name: boundless-operator.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: Addon is the Schema for the addons API
      displayName: Addon
      kind: Addon
      name: addons.boundless.mirantis.com
      version: v1alpha1
    - description: Blueprint is the Schema for the blueprints API
      displayName: Blueprint
      kind: Blueprint
      name: blueprints.boundless.mirantis.com
      version: v1alpha1
    - description: Ingress is the Schema for the ingresses API
      displayName: Ingress
      kind: Ingress
      name: ingresses.boundless.mirantis.com
      version: v1alpha1
    - description: Manifest is the Schema for the manifests API
      displayName: Manifest
      kind: Manifest
      name: manifests.boundless.mirantis.com
      version: v1alpha1
  description: boundless operator
  displayName: boundless-operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - app
  - operator
  links:
  - name: Boundless Operator
    url: https://boundless-operator.domain
  maturity: alpha
  provider:
    name: Mirantis
  version: 0.0.0
