apiVersion: blueprint.mirantis.com/v1alpha1
kind: Addon
metadata:
  labels:
    app.kubernetes.io/name: addon
    app.kubernetes.io/instance: addon-sample
    app.kubernetes.io/part-of: blueprint-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: blueprint-operator
  name: addon-sample
spec:
  # TODO(user): Add fields here
