apiVersion: blueprint.mirantis.com/v1alpha1
kind: Blueprint
metadata:
  labels:
    app.kubernetes.io/name: blueprint
    app.kubernetes.io/instance: blueprint-sample
    app.kubernetes.io/part-of: blueprint-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: blueprint-operator
  name: blueprint-sample
spec:
  # TODO(user): Add fields here
