name: e2e

on:
  workflow_call:

jobs:
  e2e:
    name: e2e
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Load environment
        uses: c-py/action-dotenv-to-setenv@v4
        with:
          env-file: .github/development.env

      - name: Setup Go ${{ env.GO_VERSION }}
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: ${{ env.IMAGE }}
          path: /tmp

      - name: Load docker image
        working-directory: .
        run: docker load --input /tmp/${{ env.IMAGE }}.tar

#      - name: Tag the image with the commit sha
#        run:
#          COMMIT_SHA=$(git rev-parse --short "$GITHUB_SHA")
#          docker tag ${{ env.REGISTRY }}/${{ env.ORG }}/${{ env.IMAGE }}:latest ${{ env.REGISTRY }}/${{ env.ORG }}/${{ env.IMAGE }}:$COMMIT_SHA

      - name: Run E2E tests
        run: |
          make e2e
