name: e2e

on:
  workflow_call:

jobs:
  e2e:
    name: e2e
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Load environment
        uses: c-py/action-dotenv-to-setenv@v4
        with:
          env-file: .github/development.env

      - name: Setup Go ${{ env.GO_VERSION }}
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: ${{ env.IMAGE }}
          path: /tmp

      - name: Load docker image
        working-directory: .
        run: docker load --input /tmp/${{ env.IMAGE }}.tar

      - name: Tag the docker image
        run: |
          COMMIT_SHA=$(git rev-parse --short "$GITHUB_SHA")
          echo ${{ env.IMAGE }}:$COMMIT_SHA
          docker tag ${{ env.REGISTRY }}/${{ env.ORG }}/${{ env.IMAGE }}:latest ${{ env.IMAGE }}:$COMMIT_SHA

      - name: Generate the operator manifest
        run: IMG="${{ env.IMAGE }}:$COMMIT_SHA" make build-operator-manifest

      - name: Run E2E tests
        run: |
          COMMIT_SHA=$(git rev-parse --short "$GITHUB_SHA")
          make e2e E2E_TEST_FLAG="-test.v -test.failfast -test.timeout 20m --img ${{ env.IMAGE }}:$COMMIT_SHA"
