name: Merge

on:
  push:
    branches:
      - main

jobs:
  vet:
    uses: ./.github/workflows/vet.yml
  unit-test:
      uses: ./.github/workflows/unit.yml
  build:
    uses: ./.github/workflows/build.yml
  # This was tested to be working but is not used because ghcr.io is currently our public release registry
  # push-to-ghcr:
  #   if: ${{ always() && contains(join(needs.*.result, ','), 'success') }} # if all need jobs are successful
  #   needs: [vet, unit-test, build]
  #   uses: ./.github/workflows/push-to-ghcr.yml
