name: PR

on:
  pull_request:
    types: ['opened', 'reopened', 'synchronize']
    branches: [ "main" ]
    paths:
      - '**' # all files otherwise excludes wont work
      - '!**/**/*.md' # ignore markdown files
      - '!demo/**' # ignore demos folder
      - '!sample/**' # ignore samples folder
      - '!example/**' # ignore examples folder

jobs:
  vet:
    uses: ./.github/workflows/vet.yml
  test:
    uses: ./.github/workflows/test.yml
  e2e:
    if: ${{ always() && contains(join(needs.*.result, ','), 'success') }} # if all `needs` jobs are successful
    needs: [vet, test, build]
    uses: ./.github/workflows/e2e.yml
  build:
    uses: ./.github/workflows/build.yml
  cleanup:
    if: ${{ always() }}
    needs: [vet, test, e2e, build]
    secrets: inherit
    uses: ./.github/workflows/cleanup.yml
