name: PR

on:
  pull_request:
    types: ['opened', 'reopened', 'synchronize']
    branches: [ "main" ]
    paths:
      - '**' # all files otherwise excludes wont work
      - '!**/**/*.md' # ignore markdown files

jobs:
  vet:
    uses: ./.github/workflows/jobs/vet.yml
  unit-test:
      uses: ./.github/workflows/jobs/unit.yml
  build:
    uses: ./.github/workflows/jobs/build.yml
