name: Push docker images

on:
  workflow_call:

jobs:
  # push-latest:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v3

  #     - name: Load environment
  #       uses: c-py/action-dotenv-to-setenv@v4
  #       with:
  #         env-file: .github/development.env

  #     - name: Log in to the Container registry
  #       uses: docker/login-action@v3.0.0
  #       with:
  #         registry: ${{ env.REGISTRY }}
  #         username: ${{ github.actor }}
  #         password: ${{ secrets.GITHUB_TOKEN }}

  #     - name: Download artifact
  #       uses: actions/download-artifact@v3
  #       with:
  #         name: ${{ env.IMAGE }}
  #         path: /tmp

  #     - name: Load docker image
  #       working-directory: .
  #       run: docker load --input /tmp/${{ env.IMAGE }}.tar

  #     - name: Push latest image to ${{ env.REGISTRY }}
  #       working-directory: .
  #       run: make docker-push

  push-dev:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Load environment
        uses: c-py/action-dotenv-to-setenv@v4
        with:
          env-file: .github/development.env

      - name: Log in to the Container registry
        uses: docker/login-action@v3.0.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: ${{ env.IMAGE }}
          path: /tmp

      - name: Load docker image
        working-directory: .
        run: docker load --input /tmp/${{ env.IMAGE }}.tar

      - name: Push SHA image to ${{ env.REGISTRY }}
        if: ${{ github.event_name == 'push' }}
        working-directory: .
        run: |
          COMMIT_SHA=$(git rev-parse --short "$GITHUB_SHA")
          echo $COMMIT_SHA
          docker tag ${{ env.REGISTRY }}/${{ env.ORG }}/${{ env.IMAGE }}:latest ${{ env.REGISTRY }}/${{ env.ORG }}/${{ env.IMAGE }}:$COMMIT_SHA
          docker push ${{ env.REGISTRY }}/${{ env.ORG }}/${{ env.IMAGE }}:$COMMIT_SHA
