name: Release

on:
  release:
    types: [prereleased]

jobs:
  vet:
    uses: ./.github/workflows/vet.yml
  unit-test:
    uses: ./.github/workflows/unit.yml
  e2e:
    uses: ./.github/workflows/e2e.yml
  build:
    uses: ./.github/workflows/build.yml
  push-to-ghcr:
    if: ${{ always() && contains(join(needs.*.result, ','), 'success') }} # if all `needs` jobs are successful
    needs: [vet, unit-test, e2e, build]
    uses: ./.github/workflows/push-to-ghcr.yml
