name: Build Boundless Operator Docker Image

on:
  push:
    branches: [ "main" ]
  pull_request:
    types: [opened, reopened]
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v3.0.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build docker image
        working-directory: .
        run: make docker-build

      - name: Push docker image to ghcr.io
        working-directory: .
        run: make docker-push
