name: Run Unit and Integration Tests

on:
  workflow_call:
    outputs:
      coverage_artifact_url:
        description: 'url of coverage artifact'
        value: ${{ jobs.tests.outputs.artifact-url }}
  push:
    branches:
      - 'main'

jobs:
  tests:
    runs-on: ubuntu-latest
    outputs:
      artifact-url: ${{ steps.artifact_upload.outputs.artifact-url }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Load environment
        uses: c-py/action-dotenv-to-setenv@v4
        with:
          env-file: .github/development.env

      - name: Setup Go ${{ env.GO_VERSION }}
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Run Unit Tests
        working-directory: .
        run: make unit

      - name: Archive code coverage results
        uses: actions/upload-artifact@v4
        id: artifact_upload
        with:
          name: code-coverage
          path: coverage.*

      - name: Update coverage badge
        uses: ncruces/go-coverage-report@v0
        if: github.ref == 'refs/heads/main'
        with:
          report: false
          chart: false
          amend: true
          badge-style: flat
          coverage-file: coverage.txt

      - name: Run Integration Tests
        working-directory: .
        run: make integration
